from typing import Protocol
from sar.domain.models import Artifact, Notification, Period, ReportData


class MonitoringGateway(Protocol):
    def hosts(self) -> list[dict]: ...
    def items(self, host_id: str) -> list[dict]: ...
    def history(self, item_id: str, start: int, end: int) -> list[dict]: ...
    def trends(self, item_id: str, start: int, end: int) -> list[dict]: ...
    def events(self, host_id: str, start: int, end: int) -> list[dict]: ...
    def recoveries(self, ids: list[str]) -> list[dict]: ...


class DocumentRenderer(Protocol):
    def report(self, data: list[ReportData], period: Period) -> bytes: ...
    def invoice(self, data: dict, template) -> bytes: ...


class ArtifactStore(Protocol):
    def save(self, data: bytes, filename: str) -> Artifact: ...
    def read(self, identifier: str) -> bytes: ...


class NotificationGateway(Protocol):
    def send(self, notification: Notification) -> None: ...


class SecretProvider(Protocol):
    def get(self, name: str) -> str | None: ...


class Scheduler(Protocol):
    def synchronize(self, schedules) -> None: ...


class UnitOfWork(Protocol):
    def __enter__(self): ...
    def __exit__(self, *args): ...
