#!/bin/sh
# Root-owned, immutable launcher invoked only by the dedicated sar-cron user's crontab.
set -eu
case "${1-}" in ''|*[!0-9]*) exit 64;; esac
[ "$#" -eq 1 ] || exit 64
exec /usr/bin/sudo -n /usr/local/libexec/sar-start-schedule "$1"
